### ISSUE TITLE
README is to be updated

### ISSUE THREAD

**Issue by JoseSunoj** [rlennon/mscplacprj2021#2]
We have to update The README.md file as soon as possible.

**Comment by JoseSunoj** [comment]
Please give inputs.

**Comment by sharonO13** [comment]
Added updates on Slack Communications, Branching and versioning and Scrum master rotation.

Open items still include Sprint planning, backlog refinements Retro, Demo tool

**Comment by JoseSunoj** [comment]
To be discussed further before completing the remaining items.
