### ISSUE TITLE
8 - Move documentation from Branch to Wiki 

### ISSUE THREAD

**Issue by sharonO13** [rlennon/mscplacprj2021#23]
As a developer I need to have a separate space to manage documentation that does not cause confusion with the Gitflow Branching Strategy. 

- Take all documentation from Github (check all branches) and move to Wiki
- Delete Documentation branch
- Remove documentation from any branches

Dependencies
Determine the method of storing images for the wiki as they can only be linked and not attached

Acceptance Criteria
All documentation is moved to the Wiki 
Documentation branch is deleted and documentatio removed from any branches

**Comment by sharonO13** [comment]
Update to remove readme

**Comment by sharonO13** [comment]
Container security and security merged - updated security tools to go with codacy for static code analysis, other tools for deployment of docker image

Confirm if credentials needed

**Comment by JoseSunoj** [comment]
docs folder was removed from all branches.
